### PR TITLE
When appropriate changed []float64 to Coord in order to provide some semantics

### PR DESCRIPTION
**Pull request by jesseeichar**
I found that I would sometimes it was not clear the meaning of float64 since it is used everywhere with different meanings. Sometimes a coordinate and should have a specific number of ordinates in this case and other times as the float coord representation of an object.

The PR adds the Coord type (just []float64) primarily in order to add semantic meaning but it also has the benefit of providing compile time checking.

I am thinking that a similar PR for a FlatCoord or Coords  type could be useful.

### CODE REVIEW

**Comment by jesseeichar** [comment]
travis complains when running `go vet ./...` but locally I don't get any errors.  I am looking into it.  I am using 1.5.1 I will see if there is a difference between that version and the version on travis.

**Comment by jesseeichar** [comment]
I downloaded 1.4.1 and the change is kind I had to make is a little silly.  

It seems that vet for 1.4.1 doesn't like geom.Coord{1,2,3}.  but it is ok with: []geom.Coord{{1,2,3},{2,2,2}}

So to make it pass vet I had to change geom.Coord{1,2} to []float64{1,2}.  What do we want?  for it to pass vet on 1.4.1 or change travis to use 1.5.1?

**Comment by twpayne** [comment]
LGTM - this definitely improves the readability of the code and the extra type checking is welcome.

I wondered if would make interoperability with other Go libraries trickier. `[]float64` is a built-in Go type, whereas `geom.Coord` is specific to this package, meaning you might need a lot of explicit typecasts to convert between the two. However, I checked a few [Go GIS libraries](https://github.com/golang/go/wiki/Projects#gis) and they already use their own custom data structures, so there's no interoperability to be gained by using `[]float64`.
 
Let's use the most recent version of Go (1.5.2) for `go vet`. I'll open a PR for this so you can rebase and submit.

**Comment by twpayne** [comment]
#2 is merged so you should be good to go for a rebase and merge.

**Comment by jesseeichar** [comment]
Travis seems happy again.  Thanks for the update.

**Comment by twpayne** [comment]
Please merge!

**Comment by twpayne** [comment]
Caveat: I think you also need to update README.md.

**Comment by jesseeichar** [comment]
That's why we have reviews :)

**Pull request merged**
