### PR TITLE
Added WKT decoding (Support for WKT #47)

### PR DESCRIPTION
**Pull request by LarsGH**
Fix for issue #47 (Support for WKT)

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks for the PR. This looks very promising.

Initial review:

* Please make the suggestions made by `go-critic`.
* This looks like its quite sensitive to whitespace. It should be able to parse `POINT  EMPTY` for example (with an arbitrary whitespace between `POINT` and `EMPTY`.
* Please the standard way of documenting Go code, as described in [this blog post](https://blog.golang.org/godoc).

Thanks again - this has great potential.

**Comment by LarsGH** [comment]
Thanks for your feedback! I am new to Go and just tried the standard "Go for Visual Studio Code" where linting seems to be different from go-critic.

- The go-critic suggestions are now implemented
- Arbitrary whitespaces are already working (see new test: TestUnmarshalEmptyGeomWithArbitrarySpaces). I guess you tried that with the previous test and the encoding did not match the WKT?
- Regarding documentation I guess you meant documenting the package and not using "/* */"-comments? Fixed that too.

**Comment by twpayne** [comment]
Thank you! This looks really excellent. Please give me a bit of time to review it in detail (there are a lot of changes) but this is a fantastic valuable contribution :)

**Comment by twpayne** [comment]
Thanks for this great contribution! There are a few associated cleanups that I'd like to do which I'll do in a follow-up PR.

**Pull request merged**
