### PR TITLE
Use sqlmock instead of sqlite3

### PR DESCRIPTION
**Pull request by twpayne**

### CODE REVIEW

**Comment by twpayne** [comment]
@jesseeichar go-geom is now back to being pure Go, no native code in the dependencies.

**Comment by jesseeichar** [comment]
How am I supposed to build this?  I just updated to it but `go get` doesn't seem to download it for some reason.
Any advice?

**Comment by twpayne** [comment]
It should be a normal Go library, just like any other. What is the output of
```
$ go get -u -v gopkg.in/DATA-DOG/go-sqlmock.v1
```
?

**Comment by jesseeichar** [comment]
full command was:

    C:\dev\go\src\github.com\twpayne\go-geom>go get -u -v
github.com\twpayne\go-geom (download)

As you can see I ran it from the go-geom directory

**Comment by jesseeichar** [comment]
Ooops looking closer you asked me to explicitly request the one package

**Comment by jesseeichar** [comment]
So running that command seemed to have fixed it.  I had expected it to do it automatically like with the sql lite package.  

We should add that to a README then

**Comment by twpayne** [comment]
`go get -u` only gets/updates the requirements for the current package. I think what's needed is `go get -u ./...` which will include all sub-packages.

**Pull request merged**
